export const stocks = [
    [
        {
            "id": 2,
            "Symbol": "MSFT",
            "AssetType": "Common Stock",
            "Name": "Microsoft Corporation",
            "Description": "Microsoft Corporation is an American multinational technology company which produces computer software, consumer electronics, personal computers, and related services. Its best known software products are the Microsoft Windows line of operating systems, the Microsoft Office suite, and the Internet Explorer and Edge web browsers. Its flagship hardware products are the Xbox video game consoles and the Microsoft Surface lineup of touchscreen personal computers. Microsoft ranked No. 21 in the 2020 Fortune 500 rankings of the largest United States corporations by total revenue; it was the world's largest software maker by revenue as of 2016. It is considered one of the Big Five companies in the U.S. information technology industry, along with Google, Apple, Amazon, and Facebook.",
            "CIK": "789019",
            "Exchange": "NASDAQ",
            "Currency": "USD",
            "Country": "USA",
            "Sector": "TECHNOLOGY",
            "Industry": "SERVICES-PREPACKAGED SOFTWARE",
            "Address": "ONE MICROSOFT WAY, REDMOND, WA, US",
            "OfficialSite": "https://www.microsoft.com",
            "FiscalYearEnd": "June",
            "LatestQuarter": "2024-12-31",
            "MarketCapitalization": "2879180243000",
            "EBITDA": "142041006000",
            "PERatio": "31.26",
            "PEGRatio": "1.659",
            "BookValue": "40.71",
            "DividendPerShare": "3.16",
            "DividendYield": "0.0089",
            "EPS": "12.39",
            "RevenuePerShareTTM": "35.22",
            "ProfitMargin": "0.354",
            "OperatingMarginTTM": "0.455",
            "ReturnOnAssetsTTM": "0.146",
            "ReturnOnEquityTTM": "0.343",
            "RevenueTTM": "261802000000",
            "GrossProfitTTM": "181714993000",
            "DilutedEPSTTM": "12.39",
            "QuarterlyEarningsGrowthYOY": "0.102",
            "QuarterlyRevenueGrowthYOY": "0.123",
            "AnalystTargetPrice": "489.32",
            "AnalystRatingStrongBuy": "15",
            "AnalystRatingBuy": "40",
            "AnalystRatingHold": "6",
            "AnalystRatingSell": "0",
            "AnalystRatingStrongSell": "0",
            "TrailingPE": "31.26",
            "ForwardPE": "25",
            "PriceToSalesRatioTTM": "11.0",
            "PriceToBookRatio": "9.19",
            "EVToRevenue": "10.6",
            "EVToEBITDA": "19.41",
            "Beta": "1",
            "52WeekHigh": "465.64",
            "52WeekLow": "344.79",
            "50DayMovingAverage": "387.58",
            "200DayMovingAverage": "415.7",
            "SharesOutstanding": "7433980000",
            "DividendDate": "2025-06-12",
            "ExDividendDate": "2025-05-15",
        },
        {
            "id": 3,
            "Symbol": "GOOGL",
            "AssetType": "Common Stock",
            "Name": "Alphabet Inc Class A",
            "Description": "Alphabet Inc. is an American multinational conglomerate headquartered in Mountain View, California. It was created through a restructuring of Google on October 2, 2015, and became the parent company of Google and several former Google subsidiaries. The two co-founders of Google remained as controlling shareholders, board members, and employees at Alphabet. Alphabet is the world's fourth-largest technology company by revenue and one of the world's most valuable companies.",
            "CIK": "1652044",
            "Exchange": "NASDAQ",
            "Currency": "USD",
            "Country": "USA",
            "Sector": "TECHNOLOGY",
            "Industry": "SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC.",
            "Address": "1600 AMPHITHEATRE PARKWAY, MOUNTAIN VIEW, CA, US",
            "OfficialSite": "https://abc.xyz",
            "FiscalYearEnd": "December",
            "LatestQuarter": "2024-12-31",
            "MarketCapitalization": "1954986721000",
            "EBITDA": "129496998000",
            "PERatio": "19.79",
            "PEGRatio": "0.972",
            "BookValue": "26.62",
            "DividendPerShare": "0.8",
            "DividendYield": "0.0051",
            "EPS": "8.05",
            "RevenuePerShareTTM": "28.41",
            "ProfitMargin": "0.286",
            "OperatingMarginTTM": "0.34",
            "ReturnOnAssetsTTM": "0.167",
            "ReturnOnEquityTTM": "0.329",
            "RevenueTTM": "350018011000",
            "GrossProfitTTM": "203712004000",
            "DilutedEPSTTM": "8.05",
            "QuarterlyEarningsGrowthYOY": "0.309",
            "QuarterlyRevenueGrowthYOY": "0.118",
            "AnalystTargetPrice": "202.34",
            "AnalystRatingStrongBuy": "14",
            "AnalystRatingBuy": "41",
            "AnalystRatingHold": "12",
            "AnalystRatingSell": "0",
            "AnalystRatingStrongSell": "0",
            "TrailingPE": "19.79",
            "ForwardPE": "17.48",
            "PriceToSalesRatioTTM": "5.59",
            "PriceToBookRatio": "5.83",
            "EVToRevenue": "5.25",
            "EVToEBITDA": "13.56",
            "Beta": "1.035",
            "52WeekHigh": "206.81",
            "52WeekLow": "140.53",
            "50DayMovingAverage": "164.62",
            "200DayMovingAverage": "172.43",
            "SharesOutstanding": "5833000000",
            "DividendDate": "2025-03-17",
            "ExDividendDate": "2025-03-10",
        },
        {
            "id": 4,
            "Symbol": "NFLX",
            "AssetType": "Common Stock",
            "Name": "Netflix Inc",
            "Description": "Netflix, Inc. is an American over-the-top content platform and production company headquartered in Los Gatos, California. Netflix was founded in 1997 by Reed Hastings and Marc Randolph in Scotts Valley, California. The company's primary business is a subscription-based streaming service offering online streaming from a library of films and television series, including those produced in-house.",
            "CIK": "1065280",
            "Exchange": "NASDAQ",
            "Currency": "USD",
            "Country": "USA",
            "Sector": "TRADE &amp; SERVICES",
            "Industry": "SERVICES-VIDEO TAPE RENTAL",
            "Address": "100 WINCHESTER CIRCLE, ., LOS GATOS, CA, US",
            "OfficialSite": "https://www.netflix.com",
            "FiscalYearEnd": "December",
            "LatestQuarter": "2025-03-31",
            "MarketCapitalization": "466796085000",
            "EBITDA": "11453826000",
            "PERatio": "51.74",
            "PEGRatio": "1.876",
            "BookValue": "56.45",
            "DividendPerShare": "None",
            "DividendYield": "None",
            "EPS": "21.2",
            "RevenuePerShareTTM": "93.79",
            "ProfitMargin": "0.231",
            "OperatingMarginTTM": "0.318",
            "ReturnOnAssetsTTM": "0.138",
            "ReturnOnEquityTTM": "0.408",
            "RevenueTTM": "40173326000",
            "GrossProfitTTM": "18848788000",
            "DilutedEPSTTM": "21.2",
            "QuarterlyEarningsGrowthYOY": "0.252",
            "QuarterlyRevenueGrowthYOY": "0.125",
            "AnalystTargetPrice": "1097.05",
            "AnalystRatingStrongBuy": "7",
            "AnalystRatingBuy": "25",
            "AnalystRatingHold": "13",
            "AnalystRatingSell": "0",
            "AnalystRatingStrongSell": "2",
            "TrailingPE": "51.74",
            "ForwardPE": "42.19",
            "PriceToSalesRatioTTM": "11.62",
            "PriceToBookRatio": "18.59",
            "EVToRevenue": "11.28",
            "EVToEBITDA": "16.75",
            "Beta": "1.547",
            "52WeekHigh": "1101",
            "52WeekLow": "544.25",
            "50DayMovingAverage": "961.41",
            "200DayMovingAverage": "826.52",
            "SharesOutstanding": "425571000",
            "DividendDate": "None",
            "ExDividendDate": "None",
        },
        {
            "id": 1,
            "Symbol": "AAPL",
            "AssetType": "Common Stock",
            "Name": "Apple Inc",
            "Description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software, and online services. Apple is the world's largest technology company by revenue (totalling $274.5 billion in 2020) and, since January 2021, the world's most valuable company. As of 2021, Apple is the world's fourth-largest PC vendor by unit sales, and fourth-largest smartphone manufacturer. It is one of the Big Five American information technology companies, along with Amazon, Google, Microsoft, and Facebook.",
            "CIK": "320193",
            "Exchange": "NASDAQ",
            "Currency": "USD",
            "Country": "USA",
            "Sector": "TECHNOLOGY",
            "Industry": "ELECTRONIC COMPUTERS",
            "Address": "ONE INFINITE LOOP, CUPERTINO, CA, US",
            "OfficialSite": "https://www.apple.com",
            "FiscalYearEnd": "September",
            "LatestQuarter": "2024-12-31",
            "MarketCapitalization": "3130155074000",
            "EBITDA": "137352004000",
            "PERatio": "33.07",
            "PEGRatio": "2.008",
            "BookValue": "4.438",
            "DividendPerShare": "0.99",
            "DividendYield": "0.0049",
            "EPS": "6.3",
            "RevenuePerShareTTM": "25.97",
            "ProfitMargin": "0.243",
            "OperatingMarginTTM": "0.345",
            "ReturnOnAssetsTTM": "0.225",
            "ReturnOnEquityTTM": "1.365",
            "RevenueTTM": "395760009000",
            "GrossProfitTTM": "184102994000",
            "DilutedEPSTTM": "6.3",
            "QuarterlyEarningsGrowthYOY": "0.101",
            "QuarterlyRevenueGrowthYOY": "0.04",
            "AnalystTargetPrice": "236.23",
            "AnalystRatingStrongBuy": "7",
            "AnalystRatingBuy": "21",
            "AnalystRatingHold": "14",
            "AnalystRatingSell": "2",
            "AnalystRatingStrongSell": "1",
            "TrailingPE": "33.07",
            "ForwardPE": "27.93",
            "PriceToSalesRatioTTM": "7.91",
            "PriceToBookRatio": "46.04",
            "EVToRevenue": "7.87",
            "EVToEBITDA": "22.69",
            "Beta": "1.259",
            "52WeekHigh": "259.81",
            "52WeekLow": "168.32",
            "50DayMovingAverage": "219.52",
            "200DayMovingAverage": "227.72",
            "SharesOutstanding": "15022100000",
            "DividendDate": "2025-02-13",
            "ExDividendDate": "2025-02-10",
        }
    ]
];
